apiVersion: v1
kind: Namespace
metadata:
  name: offgrid
  labels:
    name: offgrid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: offgrid-config
  namespace: offgrid
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  REDIS_URL: "redis://redis:6379"
  NEXT_PUBLIC_API_URL: "https://api.offgrid.example.com"
  NEXT_PUBLIC_WP_URL: "https://cms.offgrid.example.com"
  WORDPRESS_API_URL: "http://wordpress/wp-json"
  AI_SERVICE_URL: "http://ai-service:8000"
