apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: offgrid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: offgrid/ai-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: offgrid-config
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: offgrid-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: offgrid-secrets
              key: ANTHROPIC_API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: offgrid-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: offgrid
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ai-service
  type: ClusterIP
