---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: offgrid
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://ai-service:8000"
  NEXT_PUBLIC_WP_URL: "http://wordpress"
  WORDPRESS_API_URL: "http://wordpress/wp-json"
  AI_SERVICE_URL: "http://ai-service:8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: offgrid
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo "Waiting for WordPress..."
              until nc -z wordpress 80; do sleep 2; done
              echo "Waiting for AI Service..."
              until nc -z ai-service 8000; do sleep 2; done
              echo "All dependencies ready!"
      containers:
        - name: frontend
          image: offgrid/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NODE_ENV
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_WP_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NEXT_PUBLIC_WP_URL
            - name: WORDPRESS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: WORDPRESS_API_URL
            - name: AI_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: AI_SERVICE_URL
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: offgrid
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: frontend
