apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: offgrid

resources:
  - namespace.yaml
  - mysql.yaml
  - redis.yaml
  - wordpress.yaml
  - ai-service.yaml
  - frontend.yaml
  - ingress.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: offgrid
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
# Deployment order for dependencies
# 1. Namespace
# 2. MySQL, Redis (stateful services)
# 3. WordPress (depends on MySQL)
# 4. AI Service (depends on Redis)
# 5. Frontend (depends on WordPress and AI Service)
# 6. Ingress (exposes services)
