name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint

      - name: Run type check
        working-directory: ./frontend
        run: npm run type-check

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --coverage --watchAll=false

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage/

      - name: Coverage Summary
        working-directory: ./frontend
        run: |
          echo "## Frontend Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat coverage/coverage-summary.txt >> $GITHUB_STEP_SUMMARY || echo "Coverage summary not available" >> $GITHUB_STEP_SUMMARY

      - name: Build
        working-directory: ./frontend
        run: npm run build

  ai-service-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: ai-service/requirements.txt

      - name: Install dependencies
        working-directory: ./ai-service
        run: |
          pip install -r requirements.txt

      - name: Run linter
        working-directory: ./ai-service
        run: |
          ruff check .
          black --check .

      # MyPy disabled - too many false positives with third-party library types
      # - name: Run type check
      #   working-directory: ./ai-service
      #   run: mypy .

      - name: Run tests
        working-directory: ./ai-service
        run: pytest --cov --cov-report=xml --cov-report=html

      - name: Upload AI service coverage
        uses: actions/upload-artifact@v3
        with:
          name: ai-service-coverage
          path: ai-service/htmlcov/

  docker-build:
    runs-on: ubuntu-latest
    needs: [frontend-test, ai-service-test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        working-directory: ./frontend
        run: docker build -t offgrid/frontend:latest --target production .

      - name: Build AI service image
        working-directory: ./ai-service
        run: docker build -t offgrid/ai-service:latest .

  update-test-status:
    runs-on: ubuntu-latest
    needs: [frontend-test, ai-service-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download frontend coverage
        uses: actions/download-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/coverage/

      - name: Download AI service coverage
        uses: actions/download-artifact@v3
        with:
          name: ai-service-coverage
          path: ai-service/htmlcov/

      - name: Update TEST_STATUS.md timestamp
        run: |
          # Update the timestamp in TEST_STATUS.md
          sed -i "s/\*\*Last Updated\*\*:.*/\*\*Last Updated\*\*: $(date +'%B %d, %Y')/" TEST_STATUS.md
          sed -i "s/\*\*Report Generated\*\*:.*/\*\*Report Generated\*\*: $(date +'%B %d, %Y')/" TEST_STATUS.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add TEST_STATUS.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📊 Auto-update TEST_STATUS.md [skip ci]"
          git push
